export const letters = [
    `I want you to know this: these letters are for you—each one a small, inadequate attempt to express emotions words could never truly capture.\nYou have changed me in so many quiet, beautiful ways. Being with you reminds me that love doesn’t always have to be loud to be powerful—it can be soft and steady and consistent and still shake the foundation of a life.\n\nThese letters are a small attempt to illustrate and put into words what your presence in my life has meant to me. Each song displayed before you echoes my perspective of your soul. They are pieces of you..pieces of our connection, scattered amongst melodies .\nOn days we’re together and even more on the days we’re apart, I hope you’ll read them and listen, and remember that I am with you. That I believe in you. That no matter where life takes us, I carry your heart with me, always.\n\nWith all my love,\nZac`,
    "I've often seen graduation viewed as a frightening time in one's life\u2026the death of youth. The future is unknown, and the unknown can be terrifying. And so too is death. It is inherent of death that we know not what lies beyond it. But there is beauty in our fear. And from the ashes of our youth grows something far more valuable. What more can we ask of ourselves than to jump unapologetically and unashamedly into the unknown. To do so with passion and with vigor, and to do so in the pursuit of fulfilling a purpose beyond ourselves, is the essence of life.\n\nI ask of you now only one thing: to enter into this next chapter of your life, and to fail. I ask that you fail again and again; it is only through our defeats that we can know our greatest triumphs. And it is only in our sorrow that we can know true joy. I am so unbelievably proud of you. In your pursuit of your dreams, know that I will always be by your side. Through every failure and every fall, I will be there to lift you up once more. You are always and forever my partner in this life; and if we have nothing else, we will always have that.\n\nWith all my love,\nZac",    
    "To meet you was not to experience some flash of love at first sight, but something different...something softer and far more certain. To meet and truly begin to know you felt like remembering rather than discovering, as if our souls had known each other long before they allowed our physical selves to meet—as though my soul had been quietly waiting for yours, desperately awaiting your arrival. You entered my life not as a surprise, but as a truth I had always known—it was always going to be you.\n\nWith all my love,\nZac",
    "Without you, life loses its color. To experience life in the absence of your presence is to ache and to suffer—wishing only that I had someone to share it all with.\n\nWith all my love,\nZac",
    "How endlessly lucky am I to witness the way you turn even life’s quietest moments into memories I’ll hold forever? What a gift it is to sleep in beside you on a still Sunday morning, or to wander aimlessly about on a golden spring evening, your hand placed gently within mine. Since loving you, no longer does the notion of ordinary exist in my life.\n\nWith all my love,\nZac",
    "In your absence, I carry within me, embedded deep within the depths of my soul, your love, like sunlight in my chest. It warms me when we are apart and brings me peace in difficult times—it is a light that extends beyond even my own self, but to all those I interact with.\n\nWith all my love,\nZac",
    "Know this, always: my love for you is constant, quiet as breath, and enduring as time. I am with you—through joy and stillness, through sorrow and storm. I see within you such a tremendous passion for others and such a strength to perservere through life’s many trials. You are braver than you believe, stronger than you know, and I will walk beside you, hand in hand, through every season of your life.\n\nWith all my love,\nZac",
    "I will never stop searching for you.\n\nIn the fleeting seconds of silent gaps within my thoughts, you emerge as though a memory my soul has always known. It is you I feel in the gentle warmth of the sun’s embrace on a warm summer day and in the moon’s quiet luminescence on a cold winter night. In the innocence of each creature I encounter and in the kindness owed to those more hostile, there you are. You exist in the majesty of towering peaks and in the stubborn flicker of hope that glows in life’s darkest valleys. Wherever there is wonder, wherever there is ache, wherever there is breath—I never cease finding you. In all that this life has to offer, it is you waiting for me on the other side.\n\nMy soul is forever drawn to yours. It has always been you.\n\nWith all my love,\nZac",
    "I’ve seen you go through more in the past few years than most people face in a lifetime, and I’ve seen you grow stronger because of it. There’s something so special about the way you carry both resilience and kindness, how you still laugh freely and care so deeply. I will forever be immeasurably drawn to you—in this life and any other, you’ll always feel like home to me.\n\nWith all my love,\nZac",
    "These have been letters written from me to you.\n\nI write them knowing that, though words hold a tremendous power, they could never adequately carry within them but an essence of what I feel for you. And though I am disheartened by this inadequacy, I will not fret long, for we have a life yet to live…and we get to live it together.\n\nAnd truly, I ask you, what could be more wonderful than that?\n\nWith all my love,\nZac"
]